/* price-prom.js — то же самое, но фильтр list=prom */
const CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRhmVwX16I7aMJ6CKS_5GGu3rI915mv9VRg11ZL9pau_672ZRHNZclBQ6P7Di_TJeF42B4ULkxUg3Lt/pub?output=csv";
const LIST_FILTER = "prom";

const ENABLE_PROMOS = true;
const CSV_DELIMITER = ",";
const DISCOUNT_MODE = "current";
const fmtMoney = n => n.toLocaleString('ru-RU', { maximumFractionDigits: 0 });
const bust = url => url + (url.includes("?") ? "&" : "?") + "cb=" + Date.now();

function parseCsv(t,d){const r=[];let o=[],v="",q=!1;const p=()=>{o.push(v);v=""},a=()=>{r.push(o);o=[]};for(let i=0;i<t.length;i++){const c=t[i];if(q){if(c==='"'){if(t[i+1]==='"'){v+='"',i++}else q=!1}else v+=c}else c==='"'?q=!0:c===d?p():c==='\n'?(p(),a()):c!=='\r'&&(v+=c)}(v.length||o.length)&&(p(),a());const[h,...e]=r;if(!h)return[];const n=h.map(h=>String(h||"").trim());return e.filter(r=>r.length&&r.some(c=>String(c).trim())).map(r=>Object.fromEntries(n.map((h,i)=>[h,r[i]!=null?String(r[i]).trim():""])))}function parseRuDate(s){if(!s)return null;const m=/^(\d{2})\.(\d{2})\.(\d{4})$/.exec(s.trim());if(!m)return null;const[,d,M,y]=m;return new Date(+y,+M-1,+d)}
function isPromoActive(x,t=new Date()){if(!ENABLE_PROMOS)return!1;const s=parseRuDate(x.promo_start),e=parseRuDate(x.promo_end);if(!s||!e)return!1;const n=new Date(t.getFullYear(),t.getMonth(),t.getDate());return n>=new Date(s.getFullYear(),s.getMonth(),s.getDate())&&n<=new Date(e.getFullYear(),e.getMonth(),e.getDate())}
function computePrices(x){const b=Number(x.price)||0;let a=isPromoActive(x),p=null;if(a){if(x.promo_price!==""){const v=Number(x.promo_price);Number.isNaN(v)||(p=v)}if(null==p&&x.promo_discount!==""){const d=Number(x.promo_discount);Number.isNaN(d)||(p=Math.round(b*(1-d/100)))}null==p&&(a=!1)}return{base:b,promoActive:a,promo:p}}
function findPriceTable(){const t=Array.from(document.querySelectorAll("table"));let b=null,s=-1;for(const a of t){const h=Array.from(a.querySelectorAll("thead th, tr th")).map(th=>th.textContent.trim().toLowerCase()).join(" ");let c=0;h.includes("артикул")&&c++;h.includes("цена")&&c++;h.includes("акция")&&c++;c>s&&(s=c,b=a)}return b}
function mapColumns(t){const h=Array.from(t.querySelectorAll("thead th")),x=h.map(th=>th.textContent.trim().toLowerCase());return{ths:h,idx:{article:x.findIndex(t=>/артикул/.test(t)),name:x.findIndex(t=>/наимен/.test(t)),description:x.findIndex(t=>/описан/.test(t)),pack:x.findIndex(t=>/упак/.test(t)),pallet:x.findIndex(t=>/палет|палета/.test(t)),price:x.findIndex(t=>/цена/.test(t)),promo:x.findIndex(t=>/акци/.test(t)),image:x.findIndex(t=>/фото|image/.test(t)),link:x.findIndex(t=>/карточ|перейти|ссылка|product/.test(t))}}}
function buildRowByStructure(s,it){const{idx,ths}=s,{base,promoActive,promo}=computePrices(it),td=k=>{const el=document.createElement("td");let html="";k===idx.article?html=it.article||"":k===idx.name?html=it.name||"":k===idx.description?html=it.description||"":k===idx.pack?html=it.pack||"":k===idx.pallet?html=it.pallet||"":k===idx.price?html=fmtMoney(base):k===idx.promo?html=promoActive&&null!=promo?fmtMoney(promo):"":k===idx.image?html=it.image_url?`<img loading="lazy" src="${it.image_url}" alt="">`:"":k===idx.link&&(html=it.product_url?`<a class="urla" href="${it.product_url}" target="_blank" rel="noopener">перейти</a>`:"");return el.innerHTML=html,el};const tr=document.createElement("tr"),cols=ths.length||9;for(let c=0;c<cols;c++)tr.appendChild(td(c));return tr.dataset.base=String(Number(it.price)||0),tr.dataset.promo=null!=promo?String(promo):"",tr.dataset.promoActive=String(!!(promoActive&&null!=promo)),tr}
function renderTable(t,items){let b=t.querySelector("tbody");b||(b=document.createElement("tbody"),t.appendChild(b));b.innerHTML="";const s=mapColumns(t);items.forEach(it=>b.appendChild(buildRowByStructure(s,it)))}
function applyDiscount(p){const t=findPriceTable();if(!t)return;const b=t.querySelector("tbody");if(!b)return;const v=Math.max(0,Math.min(99,Number(p)||0));b.querySelectorAll("tr").forEach(tr=>{const base=Number(tr.dataset.base||0),pa=tr.dataset.promoActive==="true",pp=tr.dataset.promo?Number(tr.dataset.promo):null;let target=base;"current"===DISCOUNT_MODE&&(target=pa&&null!=pp?pp:base),"promoOnly"===DISCOUNT_MODE&&(target=pa&&null!=pp?pp:base),"baseOnly"===DISCOUNT_MODE&&(target=base);const disc=Math.round(target*(1-v/100)),{idx}=mapColumns(t),tds=tr.children;pa&&null!=pp&&idx.promo>=0&&tds[idx.promo]?tds[idx.promo].textContent=fmtMoney(disc):idx.price>=0&&tds[idx.price]&&(tds[idx.price].textContent=fmtMoney(disc),idx.promo>=0&&tds[idx.promo]&&(tds[idx.promo].textContent=""))})}
function resetTable(orig){const t=findPriceTable();t&&renderTable(t,orig);const inp=document.getElementById("discount");inp&&(inp.value="")}
async function loadCsv(u){const r=await fetch(bust(u),{cache:"no-store"});if(!r.ok)throw new Error("CSV load error "+r.status);return parseCsv(await r.text(),CSV_DELIMITER)}
(async function(){try{const t=findPriceTable();if(!t)return;const raw=await loadCsv(CSV_URL),items=raw.filter(x=>(x.list||"").toString().trim().toLowerCase()===LIST_FILTER).map(x=>({article:x.article??"",name:x.name??"",description:x.description??"",pack:x.pack??"",pallet:x.pallet??"",price:x.price??"",promo_price:x.promo_price??"",promo_discount:x.promo_discount??"",promo_start:x.promo_start??"",promo_end:x.promo_end??"",image_url:x.image_url??"",product_url:x.product_url??""}));renderTable(t,items);const a=document.getElementById("applyDiscount"),r=document.getElementById("resetDiscount"),i=document.getElementById("discount");a&&i&&a.addEventListener("click",()=>applyDiscount(i.value));r&&r.addEventListener("click",()=>resetTable(items));setInterval(async()=>{try{const fr=await loadCsv(CSV_URL),upd=fr.filter(x=>(x.list||"").toString().trim().toLowerCase()===LIST_FILTER).map(x=>({article:x.article??"",name:x.name??"",description:x.description??"",pack:x.pack??"",pallet:x.pallet??"",price:x.price??"",promo_price:x.promo_price??"",promo_discount:x.promo_discount??"",promo_start:x.promo_start??"",promo_end:x.promo_end??"",image_url:x.image_url??"",product_url:x.product_url??""}));renderTable(t,upd)}catch(e){console.warn("Автообновление не удалось:",e)}},10*60*1000)}catch(e){console.error(e)}})();
